### PR TITLE
Added Russian translation

### PR DESCRIPTION
**Pull request by AlisaBagrii**

### CODE REVIEW

**Comment by eddiemonge** [comment]
This would have to be available in every language if we did this. I think a tweet about it would be better. Thanks though. @addyosmani

**Comment by SBoudrias** [comment]
@AlisaBagrii if you provide us with a tweet in Russian, we'll be glad to re-tweet or tweet it with the yeoman account.

**Comment by AlisaBagrii** [comment]
Thank you very much, this is really very nice of you! I think actually in twitter it will go down, and people will not know anymore that the guide is available in Russian. That's why I thought that being seen at the article will show that the tutorial is also in other language. Yeoman is very helpful and useful, I am sure a lot of people would like to contribute with other languages, if you mean this. If I knew more languages, I could offer you in all languages :)

**Comment by SBoudrias** [comment]
@AlisaBagrii you can also send a PR to add that link to our resource page http://yeoman.io/learning/resources.html

**Comment by AlisaBagrii** [comment]
Thank you very much. I will submit it now

**Pull request closed without merging**
