### PR TITLE
Fix typo

### PR DESCRIPTION
**Pull request by mischah**
… and check deploy preview.

### CODE REVIEW

**Comment by mischah** [comment]
Deploy preview ready!

Built with commit 2cbbf46f25eb9cd0b94f973bc5a4772132a06235

https://deploy-preview-746--yeoman.netlify.com

**Comment by mischah** [comment]
Re-added the »deploy preview ready!« comment in netlifys settings after having the yeoman organization. Thought it might change the user which creates the comment. But nah.

Guess its related to the one who sets this up at netlify, cause it generates a GitHub API access token on the fly.

Without the comment one would only see the deploy preview when clicking »Show all checks« in the green bordered box.

**Comment by mischah** [comment]
Okay. Deactivated the »deploy preview ready!« comment again. Will affect the next PR.

**Comment by mischah** [comment]
@SBoudrias Should we omit the »deploy preview ready!« comment for now?

One has to click the following to get to the deploy preview:
+ Show all checks
+ Details

This is okay to handle for Yeoman team members to review PRs.
But I guess someone who creates a PR will miss the possibility to see his changes in action.

What do you think?

**Comment by SBoudrias** [comment]
I just think bot comments adds a lot of noise to my notifications usually.

**Comment by mischah** [comment]
Ok, thanks for your feedback. Leaving without the comment.

**Pull request merged**
