### PR TITLE
Fix the incorrect positioning of the sidebar

### PR DESCRIPTION
**Pull request by snowjotunn**
Update script.js
Fix incorrect sidebar positioning
incorrect sidebar positioning

### CODE REVIEW

**Comment by mischah** [comment]
Thanks for the PR and sorry for being late with the review.

I can’t see the sidebar in the deploy preview of your changes:
https://deploy-preview-754--yeoman.netlify.com/codelab/index.html

**Comment by snowjotunn** [comment]
sidebar can be seen here:
https://deploy-preview-754--yeoman.netlify.com/learning/index.html

**Comment by mischah** [comment]
Ahh. Thanks. Looks good.

I just wonder, what happened to the sidebar navigation in the codelabs pages?
It also gone in the live page on http://yeoman.io/codelab/index.html 🤔 

So that is not a regression caused by your changes.

Happy to merge this, because it is definitely an improvement 👌 

But I would prefer just using `position: sticky` to handle that behavior. I’m going to open another issue for that.

**Comment by mischah** [comment]
Thanks again :octocat:

Your commit did it to the source branch and the change should be deployed in a matter of minutes.

**Comment by mischah** [comment]
The sidebar in codelabs is back with the next deployment 😘

**Pull request merged**
