### PR TITLE
Repair links and image addresses

### PR DESCRIPTION
**Pull request by kathyonu**
Repaired addresses to working.
Not familiar with <code>{{ addyLink }}</code> .. all links with it are broken still.

### CODE REVIEW

**Comment by SBoudrias** [comment]
locally or on the live server right now?

**Comment by kathyonu** [comment]
Live on the net

**Comment by SBoudrias** [comment]
I believe you tried to access all of this through the github repository. But these files are actually what is served from the website http://yeoman.io/codelab/meet-yeoman.html - and so they're not meant to link to actual github.com resources when viewed from github.

**Comment by kathyonu** [comment]
Okay, sorry for the unnecessary work.

**Pull request closed without merging**
