### PR TITLE
Add info about using Yarn to install dependencies

### PR DESCRIPTION
**Pull request by mischah**
Related to https://github.com/yeoman/generator/issues/980 and https://github.com/yeoman/generator/issues/964

### CODE REVIEW

**Comment by mischah** [comment]
Should be merged after a releasing generator v0.25.0

**Comment by SBoudrias** [comment]
Actually aiming at next release being 1.0

**Comment by mischah** [comment]
🙀

Whoa. Big news.

**Comment by mischah** [comment]
Closed in favor of #700 
… pushed my commit to doc/yeoman-generator/1.0.0 😘

**Pull request closed without merging**
