### PR TITLE
Unqualified Attribute Selectors removed; Fixes #610

### LINKED ISSUE #610: Slow Unqualified Attribute Selectors
Unqualified attribute selectors are known to be slow, so it might be interesting to avoid the use of unqualified attribute selectors.

**Why is this an issue?**

Unqualified attribute selectors, such as the one bellow, match all the page before check their attributes. So, like the universal selector they evaluate selectors from right to left.

Ex:

```
 .ex-class [type=text] {
   font-size: 16px;
 }
```

### PR DESCRIPTION
**Pull request by Siddharth11**
Normalize.css updated to latest version. All Unqualified Attribute Selectors removed to improve performance.

### CODE REVIEW

**Comment by eddiemonge** [comment]
Did you modify the normalize file or thats how the new source is?

**Comment by Siddharth11** [comment]
@eddiemonge I had to modify it. Tried it on an [online css linter](http://csslint.net/) and then removed all the the Unqualified Attribute Selectors manually.

**Comment by Siddharth11** [comment]
Thank you for your insight. I'm still curious though, how should we then solve this problem?

**Comment by SBoudrias** [comment]
@Siddharth11 My point is that it is not a problem. It's fine to have it as is.

**Pull request closed without merging**
