### PR TITLE
Added translation section, first translation in RU

### PR DESCRIPTION
**Pull request by AlisaBagrii**

### CODE REVIEW

**Comment by eddiemonge** [comment]
Again, the problem with this is we need to do multiple translation on the site if we add this. Another problem is keeping that translated version up to date. We are planning on seriously changing the codelab soon so the translation would be out of date.

**Comment by eddiemonge** [comment]
This should have a date it was translated, a note saying the Yeoman team did not translate nor do they have control over it and it may be out of date.

I also don't like how its still branded and seems like part of their site/sales pitch: 
branded

**Comment by SBoudrias** [comment]
> I also don't like how its still branded and seems like part of their site/sales pitch

Most corporate blogs kind of look like that. Personaly, I'm fine with having this in the resource page.

**Comment by AlisaBagrii** [comment]
Absolutely no problem with updating. Some plugins owners send me the information with updates and I  do it gladly. So with the tutorial i will be happy to keep it updated. I can put the date and once you send me changes, I will update it, so readers will be informed. Also there is a note, who made the translation and at the translated article I put the note about your site.

**Comment by AlisaBagrii** [comment]
Thank you very much, guys! Once you have any updates, let me know.  Also I noticed that the resource page stopped working, hope my note will help to fix it.

**Pull request merged**
